name: master
on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 0 * * 0' # 00:00 Sunday

jobs:

  test:
    name: Test (stable)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --verbose
      - name: Test rayon
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --verbose --package rayon
      - name: Test rayon-core
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --verbose --package rayon-core
      - name: Test multiple rayon-core
        run: ./ci/highlander.sh
